package com.tngtech.archunit.core.importer.testexamples.fieldaccesstointerfaces.ambiguous_in_hierarchy;

public class ChildExtendingParentWithSameInterfaceFields extends ParentClassWithSameFieldsAsInterfaces {
}
