version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.junit.vintage:junit-vintage-engine"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daily"
