import java.nio.file.Files
import java.util.jar.JarFile

plugins {
    id 'archunit.java-artifact-check-conventions'
}

ext.getExpectedPomFileContent = {
    getClass().getResourceAsStream("release_check/${project.name}.pom").text.replace('${archunit.version}', version).stripIndent()
}

ext.comparePom = { String actual ->
    println "Verifying correct POM of ${project.name}"

    String expected = getExpectedPomFileContent()
    if (actual.replaceAll("\\s", "") != expected.replaceAll("\\s", "")) {
        throw new AssertionError("""POM of artifact '${project.name}' does not match:
--------
Actual: 
${actual}
--------
Expected:
${expected}
--------
""")
    }
}

task checkPom {
    dependsOn 'generatePomFileForMavenJavaPublication'
    doLast {
        comparePom(new File(buildDir, 'publications/mavenJava/pom-default.xml').text)
    }
}
check.dependsOn(checkPom)

task checkUploadedArtifacts {
    doLast {
        def getArtifact = { String artifactId, String fullEnding ->
            def repositoryUrl = 'https://central.sonatype.com/api/v1/publisher/deployments/download'
            def artifactUrl = "$repositoryUrl/com/tngtech/archunit/$artifactId/$version/$artifactId-$version$fullEnding"
            def connection = new URL(artifactUrl).openConnection()
            def token = (project.getProperty('sonatypeUsername') + ':' + project.getProperty('sonatypePassword')).bytes.encodeBase64()
            connection.setRequestProperty("Authorization", "Bearer $token")
            return connection.inputStream
        }

        def getUploadedFile = { String artifactId, String ending, String suffix ->
            def fullEnding = (!suffix.isEmpty() ? "-${suffix}" : '') + ".${ending}"
            def tempDir = Files.createTempDirectory('release-check').toFile()
            File result = new File(tempDir, "${artifactId}${fullEnding}")
            result.bytes = getArtifact(artifactId, fullEnding).bytes
            result
        }

        def getUploadedPomFileContent = {
            getArtifact(project.name, ".pom").text.stripIndent()
        }

        def checkSourcesExist = {
            assert getUploadedFile(project.name, 'jar', 'sources') != null
        }

        def checkJavadocExists = {
            assert getUploadedFile(project.name, 'jar', 'javadoc') != null
        }

        comparePom(getUploadedPomFileContent())
        checkSourcesExist()
        checkJavadocExists()

        JarFile jarFile = new JarFile(getUploadedFile(project.name, 'jar', ''))
        checkArtifactContent(jarFile)
    }
}
rootProject.closeSonatypeStagingRepository.finalizedBy(checkUploadedArtifacts)
rootProject.releaseSonatypeStagingRepository.dependsOn(checkUploadedArtifacts)
