== Installation

To use ArchUnit, it is sufficient to include the respective JAR files in the classpath.
Most commonly, this is done by adding the dependency to your dependency management tool,
which is illustrated for Maven and Gradle below. Alternatively you
can obtain the necessary JAR files directly from
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.tngtech.archunit%22[Maven Central].

=== JUnit 4

To use ArchUnit in combination with JUnit 4, include the following dependency from
Maven Central:

[source,xml,options="nowrap"]
.pom.xml
----
<dependency>
    <groupId>com.tngtech.archunit</groupId>
    <artifactId>archunit-junit4</artifactId>
    <version>0.12.0</version>
    <scope>test</scope>
</dependency>
----

[source,options="nowrap"]
.build.gradle
----
dependencies {
    testCompile 'com.tngtech.archunit:archunit-junit4:0.12.0'
}
----

=== JUnit 5

ArchUnit's JUnit 5 artifacts follows the pattern of JUnit Jupiter. There is one artifact containing
the API, i.e. the compile time dependencies to write tests. Then there is another artifact containing
the actual `TestEngine` used at runtime. The dependencies can be obtained from Maven Central.
A typical Maven configuration could look like this:

[source,xml,options="nowrap"]
.pom.xml
----
...
<build>
    <plugins>
        ...
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.22.0</version>
        </plugin>
    </plugins>
</build>
...
<dependencies>
    ...
    <dependency>
        <groupId>com.tngtech.archunit</groupId>
        <artifactId>archunit-junit5-api</artifactId>
        <version>0.12.0</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.tngtech.archunit</groupId>
        <artifactId>archunit-junit5-engine</artifactId>
        <version>0.12.0</version>
        <scope>test</scope>
    </dependency>
</dependencies>
...
----

IMPORTANT: Unfortunately Maven lacks a test runtime scope, so the engine dependency must be added
           to the test compile scope. Adding the engine dependency to the surefire-plugin
           unfortunately does not work in the current version.

The configuration for Gradle allows to clearly distinguish a test runtime scope:

[source,options="nowrap"]
.build.gradle
----
dependencies {
    ...
    testCompile 'com.tngtech.archunit:archunit-junit5-api:0.12.0'
    testRuntime 'com.tngtech.archunit:archunit-junit5-engine:0.12.0'
}
----

=== Other Test Frameworks

ArchUnit works with any test framework that executes Java code. To use ArchUnit in such a
context, include the core ArchUnit dependency from Maven Central:

[source,xml,options="nowrap"]
.pom.xml
----
<dependency>
    <groupId>com.tngtech.archunit</groupId>
    <artifactId>archunit</artifactId>
    <version>0.12.0</version>
    <scope>test</scope>
</dependency>
----

[source,options="nowrap"]
.build.gradle
----
dependencies {
   testCompile 'com.tngtech.archunit:archunit:0.12.0'
}
----

=== Maven Plugin

There exists a Maven plugin by Société Générale to run ArchUnit rules straight from Maven. For
more information visit their GitHub repo: https://github.com/societe-generale/arch-unit-maven-plugin
