== The Core API

The Core API is itself divided into the domain objects and the actual import.

=== Import

As mentioned in <<Ideas and Concepts>> the backbone of the infrastructure is the `ClassFileImporter`,
which provides various ways to import Java classes. One way is to import packages from
the classpath, or the complete classpath via

[source,java,options="nowrap"]
----
JavaClasses classes = new ClassFileImporter().importClasspath();
----

However, the import process is completely independent of the classpath, so it would be well possible
to import any path from the file system:

[source,java,options="nowrap"]
----
JavaClasses classes = new ClassFileImporter().importPath("/some/path/to/classes");
----

The `ClassFileImporter` offers several other methods to import classes, for example locations can be
specified as URLs or as JAR files.

Furthermore specific locations can be filtered out, if they are contained in the source of classes,
but should not be imported. A typical use case would be to ignore test classes, when the classpath
is imported. This can be achieved by specifying `ImportOptions`:

[source,java,options="nowrap"]
----
ImportOption ignoreTests = new ImportOption() {
    @Override
    public boolean includes(Location location) {
        return !location.contains("/test/"); // ignore any URI to sources that contains '/test/'
    }
};

JavaClasses classes = new ClassFileImporter().withImportOption(ignoreTests).importClasspath();
----

A `Location` is principally an URI, i.e. ArchUnit considers sources as File or JAR URIs

* `file:///home/dev/my/project/target/classes/some/Thing.class`
* `jar:file:///home/dev/.m2/repository/some/things.jar!/some/Thing.class`

For the two common cases to skip importing JAR files and to skip importing test files
(for typical setups, like a Maven or Gradle build),
there already exist predefined `ImportOptions`:

[source,java,options="nowrap"]
----
new ClassFileImporter()
    .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_JARS)
    .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
    .importClasspath();
----

==== Dealing with Missing Classes

While importing the requested classes (e.g. `target/classes` or `target/test-classes`)
it can happen that a class within the scope of the import has a reference to a class outside of the
scope of the import. This will naturally happen, if the classes of the JDK are not imported,
since then for example any dependency on `Object.class` will be unresolved within the import.

At this point ArchUnit needs to decide how to treat these classes that are missing from the
import. By default, ArchUnit searches within the classpath for missing classes and if found
imports them. This obviously has the advantage that information about those classes
(which interfaces they implement, how they are annotated) is present during rule evaluation.

On the downside this additional lookup from the classpath will cost some performance and in some
cases might not make sense (e.g. if information about classes not present in the original import
is known to be unnecessary for evaluating rules).
Thus ArchUnit can be configured to create stubs instead, i.e. a `JavaClass` that has all the known
information, like the fully qualified name or the method called. However, this stub might
naturally lack some information, like superclasses, annotations or other details that cannot
be determined without importing the bytecode of this class. This behavior will also happen,
if ArchUnit fails to determine the location of a missing class from the classpath.

To find out, how to configure the default behavior, refer to <<Configuring the Resolution Behavior>>.


=== Domain

The domain objects represent Java code, thus the naming should be pretty straight forward. Most
commonly, the `ClassFileImporter` imports instances of type `JavaClass`. A rough overview looks
like this:

[plantuml, "domain-overview"]
----
skinparam componentStyle uml2

skinparam component {
  BorderColor #grey
  BackgroundColor #white
}

skinparam class {
  BorderColor #grey
  BackgroundColor #white
}

class JavaPackage
class JavaClass
class JavaMember
class JavaField
class JavaCodeUnit
class ThrowsClause
class JavaConstructor
class JavaMethod
class JavaStaticInitializer

class JavaFieldAccess
class JavaConstructorCall
class JavaMethodCall

JavaPackage *--* "1..*" JavaClass : has
JavaClass *-- "0..*" JavaMember : has
JavaMember <|-- JavaField : extends
JavaMember <|-- JavaCodeUnit : extends
JavaCodeUnit <|-- JavaConstructor : extends
JavaCodeUnit <|-- JavaMethod : extends
JavaCodeUnit <|-- JavaStaticInitializer : extends
JavaConstructor *-- "1" ThrowsClause : has
JavaMethod *-- "1" ThrowsClause : has

JavaCodeUnit *-- "0..*" JavaFieldAccess : has
JavaCodeUnit *-- "0..*" JavaMethodCall : has
JavaCodeUnit *-- "0..*" JavaConstructorCall : has
----

Most objects resemble the Java Reflection API, including inheritance relations. Thus a `JavaClass`
has `JavaMembers`, which can in turn be either `JavaField`, `JavaMethod`,
`JavaConstructor` (or `JavaStaticInitializer`). While not present within the reflection API,
it makes sense to introduce an expression for anything that can access other code, which ArchUnit
calls 'code unit', and is in fact either a method, a constructor (including the class initializer)
or a static initializer of a class (e.g. a `static { ... }` block, a static field assignment,
etc.).

Furthermore one of the most interesting features of ArchUnit that exceeds the Java Reflection API,
is the concept of accesses to another class. On the lowest level accesses can only take place
from a code unit (as mentioned, any block of executable code) to either a field (`JavaFieldAccess`),
a method (`JavaMethodCall`) or constructor (`JavaConstructorCall`).

ArchUnit imports the whole graph of classes and their relationship to each other. While checking
the accesses *from* a class is pretty isolated (the bytecode offers all this information),
checking accesses *to* a class requires the whole graph to be built first. To distinguish which
sort of access is referred to, methods will always clearly state *fromSelf* and *toSelf*.
For example, every `JavaField` allows to call `JavaField#getAccessesToSelf()` to retrieve all
code units within the graph that access this specific field. The resolution process through
inheritance is not completely straight forward. Consider for example

[plantuml, "resolution-example"]
----
skinparam componentStyle uml2

skinparam component {
  BorderColor #grey
  BackgroundColor #white
}

skinparam class {
  BorderColor #grey
  BackgroundColor #white
}

class ClassAccessing {
  void accessField()
}

class ClassBeingAccessed
class SuperClassBeingAccessed {
  Object accessedField
}

SuperClassBeingAccessed <|-- ClassBeingAccessed
ClassAccessing o-- ClassBeingAccessed

----

The bytecode will record a field access from `ClassAccessing.accessField()` to
`ClassBeingAccessed.accessedField`. However, there is no such field, since the field is
actually declared in the superclass. This is the reason why a `JavaFieldAccess`
has no `JavaField` as its target, but a `FieldAccessTarget`. In other words, ArchUnit models
the situation, as it is found within the bytecode, and an access target is not an actual
member within another class. If a member is queried for `accessesToSelf()` though, ArchUnit
will resolve the necessary targets and determine, which member is represented by which target.
The situation looks roughly like

[plantuml, "resolution-overview"]
----
skinparam componentStyle uml2

skinparam component {
  BorderColor #grey
  BackgroundColor #white
}

skinparam class {
  BorderColor #grey
  BackgroundColor #white
}

class JavaFieldAccess
class FieldAccessTarget
class JavaField
class JavaMethodCall
class MethodCallTarget
class JavaMethod
class JavaConstructorCall
class ConstructorCallTarget
class JavaConstructor

JavaFieldAccess "1" *-- "1" FieldAccessTarget : has
FieldAccessTarget "1" -- "0..1" JavaField : resolves to

JavaMethodCall "1" *-- "1" MethodCallTarget : has
MethodCallTarget "1" -- "0..*" JavaMethod : resolves to

JavaConstructorCall "1" *-- "1" ConstructorCallTarget : has
ConstructorCallTarget "1" -- "0..1" JavaConstructor : resolves to
----

Two things might seem strange at the first look.

First, why can a target resolve to zero matching members? The reason is that the set of classes
that was imported does not need to have all classes involved within this resolution process.
Consider the above example, if `SuperClassBeingAccessed` would not be imported, ArchUnit would
have no way of knowing where the actual targeted field resides. Thus in this case the
resolution would return zero elements.

Second, why can there be more than one resolved methods for method calls?
The reason for this is that a call target might indeed match several methods in those
cases, for example:

[plantuml, "diamond-example"]
----
skinparam componentStyle uml2

skinparam component {
  BorderColor #grey
  BackgroundColor #white
}

skinparam class {
  BorderColor #grey
  BackgroundColor #white
}

class A <<interface>> {
  void targetMethod()
}
class B <<interface>> {
  void targetMethod()
}
class C <<abstract>> {
}
class D {
  void callTargetMethod()
}

A <|-- C : implements
B <|-- C : implements
D -right- C : calls targetMethod()
----

While this situation will always be resolved in a specified way for a real program,
ArchUnit cannot do the same. Instead, the resolution will report all candidates that match a
specific access target, so in the above example, the call target `C.targetMethod()` would in fact
resolve to two `JavaMethods`, namely `A.targetMethod()` and `B.targetMethod()`. Likewise a check
of either `A.targetMethod.getCallsToSelf()` or `B.targetMethod.getCallsToSelf()` would return
the same call from `D.callTargetMethod()` to `C.targetMethod()`.

==== Domain Objects, Reflection and the Classpath

ArchUnit tries to offer a lot of information from the bytecode. For example, a `JavaClass`
provides details like if it is an enum or an interface, modifiers like `public` or `abstract`,
but also the source, where this class was imported from (namely the URI mentioned in the first
section). However, if information if missing, and the classpath is correct, ArchUnit offers
some convenience to rely on the reflection API for extended details. For this reason, most
`Java*` objects offer a method `reflect()`, which will in fact try to resolve the respective
object from the Reflection API. For example:

[source,java,options="nowrap"]
----
JavaClasses classes = new ClassFileImporter().importClasspath(new ImportOptions());

// ArchUnit's java.lang.String
JavaClass javaClass = classes.get(String.class);
// Reflection API's java.lang.String
Class<?> stringClass = javaClass.reflect();

// ArchUnit's public int java.lang.String.length()
JavaMethod javaMethod = javaClass.getMethod("length");
// Reflection API's public int java.lang.String.length()
Method lengthMethod = javaMethod.reflect();
----

However, this will throw an `Exception`, if the respective classes are missing on the classpath
(e.g. because they were just imported from some file path).

This restriction also applies to handling annotations in a more convenient way.
Consider the following annotation:

[source,java,options="nowrap"]
----
@interface CustomAnnotation {
    String value();
}
----

If you need to access this annotation without it being on the classpath, you must rely on

[source,java,options="nowrap"]
----
JavaAnnotation<?> annotation = javaClass.getAnnotationOfType("some.pkg.CustomAnnotation");
// result is untyped, since it might not be on the classpath (e.g. enums)
Object value = annotation.get("value");
----

So there is neither type safety nor automatic refactoring support. If this annotation is on the classpath, however,
this can be written way more naturally:

[source,java,options="nowrap"]
----
CustomAnnotation annotation = javaClass.getAnnotationOfType(CustomAnnotation.class);
String value = annotation.value();
----

ArchUnit's own rule APIs (compare <<The Lang API>>) never rely on the
classpath though. Thus the evaluation of default rules and syntax combinations, described in the
next section, does not depend on whether the classes were imported from the classpath or
some JAR / folder.
