== The Core API

The Core API is itself divided into the domain and the actual import.

=== Import

As mentioned in <<Ideas and Concepts>> the backbone of the infrastructure is the `ClassFileImporter`,
which provides various ways to import Java classes. One way is to import packages from
the classpath, or the complete classpath via

[source,java,options="nowrap"]
----
JavaClasses classes = new ClassFileImporter().importClasspath();
----

However, the import is completely independent of the classpath, so it would be well possible
to import any path from the file system:

[source,java,options="nowrap"]
----
JavaClasses classes = new ClassFileImporter().importPath("/some/path/to/classes");
----

The `ClassFileImporter` offers several other methods to import classes, for example locations can be
specified as URLs or as JAR files.

Furthermore single locations can be filtered out, if they are contained in the source of classes,
but should not be imported. A typical use case would be to ignore test classes, when the classpath
is imported.