== The Library API

The Library API offers a growing collection of predefined rules, which offer a more concise API
for more complex but common patterns, like a layered architecture or checks for cycles between
slices (compare <<What to Check>>).


=== Architectures

The entrance point for checks of common architectural styles is:

[source,java,options="nowrap"]
----
com.tngtech.archunit.library.Architectures
----

At the moment this only provides a convenient check for a layered architecture (compare
<<What to Check>>), but in the future it might be extended for styles like a hexagonal
architecture, pipes and filters, separation of business logic and technical infrastructure, etc.


=== Slices

Currently there are two "slice" rules offered by the Library API. These are basically rules
that slice the code by packages, and contain assertions on those slices. The entrance point is:

[source,java,options="nowrap"]
----
com.tngtech.archunit.library.dependencies.SlicesRuleDefinition
----

The API is based on the idea to sort classes into slices according to one or several package
infixes, and then write assertions against those slices. At the moment this is for example:

[source,java,options="nowrap"]
----
// sort classes by the first package after 'myapp'
// then check those slices for cyclic dependencies
SlicesRuleDefinition.slices().matching("..myapp.(*)..").should().beFreeOfCycles()

// checks all subpackages of 'myapp' for cycles
SlicesRuleDefinition.slices().matching("..myapp.(**)").should().notDependOnEachOther()

// sort classes by packages between 'myapp' and 'service'
// then check those slices for not having any dependencies on each other
SlicesRuleDefinition.slices().matching("..myapp.(**).service..").should().notDependOnEachOther()
----

If this constraint is too rigid, e.g. in legacy applications where the package structure is rather
inconsistent, it is possible to further customize the slice creation. This can be done by specifying
a mapping of `JavaClass` to `SliceIdentifier` where classes with the same `SliceIdentifier` will
be sorted into the same slice. Consider this example:

[source,java,options="nowrap"]
----
SliceAssignment legacyPackageStructure = new SliceAssignment() {
    // this will specify which classes belong together in the same slice
    @Override
    public SliceIdentifier getIdentifierOf(JavaClass javaClass) {
        if (javaClass.getPackageName().startsWith("com.oldapp")) {
            return SliceIdentifier.of("Legacy");
        }
        if (javaClass.getName().contains(".esb.")) {
            return SliceIdentifier.of("ESB");
        }
        // ... further custom mappings

        // if the class does not match anything, we ignore it
        return SliceIdentifier.ignore();
    }

    // this will be part of the rule description if the test fails
    @Override
    public String getDescription() {
        return "legacy package structure";
    }
};

SlicesRuleDefinition.slices().assignedFrom(legacyPackageStructure).should().beFreeOfCycles()
----


=== General Coding Rules

The Library API also offers a small set of coding rules that might be useful in various projects.
Those can be found within

[source,java,options="nowrap"]
----
com.tngtech.archunit.library.GeneralCodingRules
----

These for example contain rules not to use `java.util.logging`, not to write to `System.out`
(but use logging instead) or not to throw generic exceptions.


=== PlantUML Component Diagrams as rules

The Library API offers a feature that supports http://plantuml.com/component-diagram[PlantUML] diagrams.
This feature is located in

[source,java,options="nowrap"]
----
com.tngtech.archunit.library.plantuml
----

ArchUnit can derive rules straight from PlantUML diagrams and check to make sure that all imported
`JavaClasses` abide by the dependencies of the diagram. The respective rule can be created in the following way:

[source,java,options="nowrap"]
----
URL myDiagram = getClass().getResource("my-diagram.puml");

classes().should(adhereToPlantUmlDiagram(myDiagram, consideringAllDependencies()));
----

Diagrams supported have to be component diagrams and associate classes to components via stereotypes.
The way this works is to use the respective package identifiers (compare
`ArchConditions.onlyHaveDependenciesInAnyPackage(..)`) as stereotypes:

[plantuml, "simple-plantuml-archrule-example"]
----
[Some Source] <<..some.source..>>
[Some Target] <<..some.target..>> as target

[Some Source] --> target
----

[source,options="nowrap"]
----
@startuml
[Some Source] <<..some.source..>>
[Some Target] <<..some.target..>> as target

[Some Source] --> target
@enduml
----

Consider this diagram applied as a rule via `adhereToPlantUmlDiagram(..)`, then for example
a class `some.target.Target` accessing `some.source.Source` would be reported as a violation.

==== Configurations

There are different ways to deal with dependencies of imported classes not covered by the
diagram at all. The behavior of the PlantUML API can be configured by supplying a respective
`Configuration`:

[source,java,options="nowrap"]
----
// considers all dependencies possible (including java.lang, java.util, ...)
classes().should(adhereToPlantUmlDiagram(
        mydiagram, consideringAllDependencies())

// considers only dependencies specified in the PlantUML diagram
// (so any unknown depedency will be ignored)
classes().should(adhereToPlantUmlDiagram(
        mydiagram, consideringOnlyDependenciesInDiagram())

// considers only dependencies in any specified package
// (control the set of dependencies to consider, e.g. only com.myapp..)
classes().should(adhereToPlantUmlDiagram(
        mydiagram, consideringOnlyDependenciesInAnyPackage("..some.package.."))
----

It is possible to further customize which dependencies to ignore:

[source,java,options="nowrap"]
----
// there are further ignore flavors available
classes().should(adhereToPlantUmlDiagram(mydiagram).ignoreDependencies(predicate))
----

A PlantUML diagram used with ArchUnit must abide by a certain set of rules:

1. Components must be declared in the bracket notation (i.e. `[Some Component]`)
2. Components must have at least one (possible multiple) stereotype(s). Each stereotype in the diagram
must be unique and represent a valid package identifier (e.g. `\<<..example..>>` where `..` represents
an arbitrary number of packages; compare the core API)
3. Components may have an optional alias (e.g. `[Some Component] \<<..example..>> as myalias`)
4. Dependencies must use arrows only consisting of dashes (e.g. `-\->`)
5. Dependencies may go from left to right `-\->` or right to left `\<--`
6. Dependencies may consist of any number of dashes (e.g `\->` or `----\->`)
7. Dependencies may contain direction hints (e.g. `-up\->`) or color directives (e.g. `-[#green]\->`)

You can compare this
https://github.com/TNG/ArchUnit-Examples/blob/master/example-plain/src/test/resources/com/tngtech/archunit/exampletest/shopping_example.puml[diagram of ArchUnit-Examples].


=== Freezing Arch Rules

Often in grown projects when a new rule is introduced, there are hundreds or even thousands of violations,
way too many to fix immediately. The only way to tackle such extensive violations is to establish an
iterative approach which prevents the code base from further deterioration.

`FreezingArchRule` can help in these scenarios by recording all existing violations to a `ViolationStore`
on the first run. Consecutive runs will then only report new violations and ignore known violations.
Furthermore if violations are fixed, `FreezingArchRule` will automatically reduce the known stored
violations to prevent any regression.

==== Usage

To freeze an arbitrary `ArchRule` just wrap it into a `FreezingArchRule`:

[source,java,options="nowrap"]
----
ArchRule rule = FreezingArchRule.freeze(classes().should()./*complete ArchRule*/);
----

On the first run all violations of that rule will be stored as the current state. On consecutive runs only
new violations will be reported. By default `FreezingArchRule` will ignore line numbers, i.e. if a
violation is just shifted to a different line, it will still count as previously recorded
and will not be reported.

==== Configuration

By default `FreezingArchRule` will use a simple text based `ViolationStore` to store the violations
occurred during the first run and update fixed violations in the future. This is sufficient to add
these files to any version control system to continuously track the progress. You can configure the
location of the violation store within `archunit.properties` (compare <<Advanced Configuration>>):

[source,options="nowrap"]
.archunit.properties
----
freeze.store.default.path=/some/path/in/a/vcs/repo
----

==== Extension

`FreezingArchRule` provides two extension points to adjust the behavior to custom needs.
The first one is the `ViolationStore`, i.e. the store violations will be recorded to. The second one
is the `ViolationLineMatcher`, i.e. how `FreezingArchRule` will associate lines of stored violations
with lines of actual violations. As mentioned, by default this is a line matcher that ignores the
line numbers of violations within the same class.

===== ViolationStore

As mentioned in <<Configuration>>, the default `ViolationStore` is a simple text based store.
It can be exchanged though, for example to store violations in a database.
To provide your own implementation, implement `com.tngtech.archunit.library.freeze.ViolationStore` and
configure `FreezingArchRule` to use it. This can either be done programmatically:

[source,java,options="nowrap"]
----
FreezingArchRule.freeze(rule).persistIn(customViolationStore);
----

Alternatively it can be configured via `archunit.properties` (compare <<Advanced Configuration>>):

[source,options="nowrap"]
----
freeze.store=fully.qualified.name.of.MyCustomViolationStore
----

You can supply properties to initialize the store by using the namespace `freeze.store`. I.e. for properties

[source,options="nowrap"]
----
freeze.store.propOne=valueOne
freeze.store.propTwo=valueTwo
----

the method `ViolationStore.initialize(props)` will be called with the properties

[source,java,options="nowrap"]
----
propOne=valueOne
propTwo=valueTwo
----

===== ViolationLineMatcher

The `ViolationLineMatcher` will decide if a line of an occurred violation was actually be stored before.
As mentioned by default it will only ignore line numbers and count lines as equivalent when all other
details match. To exchange the default `ViolationLineMatcher`, you can again either do it programmatically:

[source,java,options="nowrap"]
----
FreezingArchRule.freeze(rule).associateViolationLinesVia(customLineMatcher);
----

or via `archunit.properties`:

[source,options="nowrap"]
----
freeze.lineMatcher=fully.qualified.name.of.MyCustomLineMatcher
----