package com.tngtech.archunit.testutils;

public class ExpectedNaming {
    public static Creator simpleNameOf(Class<?> clazz) {
        return new Creator(clazz.getName(), clazz.getSimpleName());
    }

    public static Creator simpleNameOfAnonymousClassOf(Class<?> clazz) {
        return new Creator(clazz.getName() + "$1", clazz.getSimpleName());
    }

    public static class Creator {
        private static final String SYNTHETIC_CLASS_HINT =
                "\n\nHint: The failing class appears to be a synthetic or anonymous class " +
                "generated by the compiler (e.g., from lambdas, switch expressions, or inner classes). " +
                "To exclude these from your rule, consider adding:\n" +
                "  .that().doNotHaveModifier(JavaModifier.SYNTHETIC)\n" +
                "or:\n" +
                "  .that().areNotAnonymousClasses()";

        private final String className;
        private final String simpleName;
        private final boolean isAnonymous;

        private Creator(String className, String simpleName) {
            this(className, simpleName, className.contains("$"));
        }

        private Creator(String className, String simpleName, boolean isAnonymous) {
            this.className = className;
            this.simpleName = simpleName;
            this.isAnonymous = isAnonymous;
        }

        public ExpectedMessage notStartingWith(String prefix) {
            return expectedClassViolation(String.format("does not have simple name starting with '%s'", prefix));
        }

        public ExpectedMessage notEndingWith(String suffix) {
            return expectedClassViolation(String.format("does not have simple name ending with '%s'", suffix));
        }

        public ExpectedMessage containing(String infix) {
            return expectedClassViolation(String.format("has simple name containing '%s'", infix));
        }

        private ExpectedMessage expectedClassViolation(String description) {
            String message = String.format("Class <%s> %s in (%s.java:0)",
                    className, description, simpleName);
            // Note: Hint message is not included in expected message for integration tests
            // The hint feature is tested separately in unit tests (ClassesShouldTest)
            return new ExpectedMessage(message);
        }
    }
}
