name: CI

on:
  push:
    branches:
      - copilot/experiment-run-publish-to-maven-local

env:
  build_java_version: 25

jobs:
  test_publishToMavenLocal:
    strategy:
      matrix:
        test_java_version:
          - 11
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Build JDK
        uses: actions/setup-java@v5.4.0
        with:
          distribution: 'zulu'
          java-version: ${{ env.build_java_version }}
      - name: Set up Test JDK
        uses: actions/setup-java@v5.4.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.test_java_version }}
      - name: Provide installed JDKs
        uses: actions/github-script@v9
        id: provideJdkPaths
        with:
          script: |
            for ( let envVarName in process.env ) {
              if (/JAVA_HOME_\d.*64/.test(envVarName)) {
                const version = envVarName.match(/JAVA_HOME_(\d+).*64/)[1];
                if (version === "${{ matrix.test_java_version }}") {
                  core.exportVariable('test_jdk_path', process.env[envVarName]);
                } else if (version === "${{ env.build_java_version }}") {
                  core.exportVariable('build_jdk_path', process.env[envVarName]);
                }
              }
            }
      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Publish to Maven Local
        run: |
          for ($i = 1; $i -le 250; $i++) {
            Write-Host "Execution number: $i"
            ./gradlew --no-configuration-cache --no-build-cache build -xtest -xspotbugsMain -xjavadoc publishToMavenLocal
          }
        shell: pwsh
        env:
          JAVA_HOME: ${{ env.build_jdk_path }}